### DISCUSSION TITLE
Interactive (hover / active) mixin

### DISCUSSION THREAD

**Discussion by slavanga** [zeixcom/ueli#5] [General]
In vorigen Projekten wurden teilweise hover und active Styles über ein spezielles Mixin umgesetzt.
Macht das Sinn und wollen so ein Mixin in ueli aufnehmen?

Pro
- Touch Devices bekommen keine Hover Styles (Hauptsächlich für iOS relevant)
- Disabled Cases autom. abgefangen

Con
- [Probleme](https://www.stefanjudis.com/today-i-learned/the-hover-media-query-can-help-to-remove-hover-styles-on-touch/#but-wait!!!) mit Multi-Input Systemen (z.B. Notebooks mit Touchscreen)
- Keine Hover Styles für IE ([Browser Support](https://caniuse.com/mdn-css_at-rules_media_hover))

```scss
/**
 * Sets :hover and :active style based on @media (hover: hover)
 */
@mixin interaction(
  $property: color,
  $value: null,
  $value-hover: $value,
  $value-active: $value
) {
  #{$property}: $value;

  @media (hover: hover) {
    &:hover {
      #{$property}: $value-hover;
    }
  }

  &:not(:disabled):not(.disabled):active {
    #{$property}: $value-active;
  }
}
```
